name: Backend CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  biome-lint:
    name: Biome Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Run Biome
        run: yarn lint

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: biome-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
